version: '3.4'

services:
  twelvefactorbookapp:
    links:
        - sqldata
    image: ${DOCKER_REGISTRY-}twelvefactorbookapp
    build:
      context: .
      dockerfile: TwelveFactorBookApp/Dockerfile
    depends_on:
        - sqldata


  sqldata:  
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        - SA_PASSWORD=1Secure*Password1
        - ACCEPT_EULA=Y
    volumes:  
        - ./data/mssql:/var/opt/mssql3  
    ports:  
        - '1433:1433'  
    expose:  
        - 1433  