version: '3.4'

services:
  twelvefactorbookapp:
    links:
        - sqlserverService
    image: ${DOCKER_REGISTRY-}twelvefactorbookapp
    build:
      context: .
      dockerfile: TwelveFactorBookApp/Dockerfile

  sqlserverService:  
    image: mcr.microsoft.com/mssql/server:2019-latest  
    hostname: 'sqlserver'  
    environment:  
        ACCEPT_EULA: Y  
        SA_PASSWORD: "BigPassw0rd"  
    volumes:  
        - ./data/mssql:/var/opt/mssql3  
    ports:  
        - '1433:1433'  
    expose:  
        - 1433  